# Base configs
baseurl: "https://dungnv01824.github.io/photography/"
url: "https://dungnv01824.github.io/photography/"
image_fulls_loc: "images/fulls"
image_thumbs_loc: "images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Viet Dung"
subtitle: "See the world through my eyes!"
author: "Viet Dung"
bio: "I am a developer and a tech aficionado from India. Love making teeny tiny apps solving tiny problems in life and now learning photography."
publicise: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/ramswaroop"
  twitter: ""
  instagram: ""
  dribbble: ""
  linkedin: ""
  github: ""
